app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

// PUBLIC
Route::get('/', array('as' => 'public.homepage',       'uses' => 'Www\MainController@homepage'));
Route::get('/article/{article_id}/{article_slug?}', array('as' => 'public.article.show',       'uses' => 'Www\ArticleController@show'));
Route::get('/category/{category_id}/{category_slug?}', array('as' => 'public.category.show',       'uses' => 'Www\ArticleController@category'));



// ADMINISTRATION
Route::get('admin/login',   array('as' => 'admin.login',       'uses' => 'Admin\DashboardController@login'));


Route::get('facebook/login',   array('as' => 'facebook.login',       'uses' => 'Auth\SocialiteController@redirectToProvider'));
Route::get('facebook/check',   array('as' => 'facebook.check',       'uses' => 'Auth\SocialiteController@handleProviderCallback'));

Route::group(array('prefix' => 'admin', 'middleware' => 'bloom.auth'), function(){
    
    //Route::get('dashboard',   array('as' => 'admin.dashboard',       'uses' => 'Admin\DashboardController@index'));
    Route::get('dashboard',   array('as' => 'admin.dashboard',       'uses' => 'Admin\DashboardController@index'));
    Route::resource('Article', 'Admin\ArticleController');
    
    Route::resource('User', 'Admin\UserController');
    Route::resource('Group', 'Admin\GroupController');
    Route::resource('Language', 'Admin\LanguageController');
    Route::resource('ArticleCategory', 'Admin\ArticleCategoryController');
   
    Route::resource('Carousel', 'Admin\CarouselController');
    Route::resource('Menu', 'Admin\MenuController');
    
    Route::get('settings',   array('as' => 'admin.settings',       'uses' => 'Admin\SettingsController@index')); 
    Route::post('settings/save',   array('as' => 'admin.settings.save',       'uses' => 'Admin\SettingsController@save')); 
    Route::get('settings/delete/{group}/{key}',   array('as' => 'admin.settings.delete',       'uses' => 'Admin\SettingsController@delete')); 
});


// RPC
Route::group(array('prefix' => 'rpc'), function(){
    
    // Autenticazione
    Route::post('login',   array('as' => 'rpc.login', 'uses' => 'Rpc\RpcAuthController@postLogin'));
    Route::get('logout',   array('as' => 'rpc.logout', 'uses' => 'Rpc\RpcAuthController@getLogout'));
    
    // Form - immagini
    Route::post('form/upload/picture',   array('as' => 'rpc.form.upload.picture', 'uses' => 'Rpc\RpcFormController@uploadPicture'));
    Route::get('form/delete/picture',   array('as' => 'rpc.form.delete.picture', 'uses' => 'Rpc\RpcFormController@deletePicture'));
    Route::get('form/load/pictures',   array('as' => 'rpc.form.load.pictures', 'uses' => 'Rpc\RpcFormController@loadPictures'));
    Route::get('form/setMain/picture',   array('as' => 'rpc.form.setmain.picture', 'uses' => 'Rpc\RpcFormController@setMainPicture'));
    Route::post('form/rename/picture',   array('as' => 'rpc.form.rename.picture', 'uses' => 'Rpc\RpcFormController@renamePicture'));
    Route::get('form/setOrder/picture',   array('as' => 'rpc.form.setorder.picture', 'uses' => 'Rpc\RpcFormController@setOrderPicture'));
    
    
    // Form - allegati
    Route::post('form/upload/attachment',   array('as' => 'rpc.form.upload.attachment', 'uses' => 'Rpc\RpcFormController@uploadAttachment'));
    Route::get('form/delete/attachment',   array('as' => 'rpc.form.delete.attachment', 'uses' => 'Rpc\RpcFormController@deleteAttachment'));
    Route::get('form/load/attachments',   array('as' => 'rpc.form.load.attachments', 'uses' => 'Rpc\RpcFormController@loadAttachments'));
    Route::post('form/rename/attachment',   array('as' => 'rpc.form.rename.attachment', 'uses' => 'Rpc\RpcFormController@renameAttachment'));
    Route::get('form/setOrder/attachment',   array('as' => 'rpc.form.setorder.attachment', 'uses' => 'Rpc\RpcFormController@setOrderAttachment'));
    
    // Menu
    Route::get('menu/loadNode/{node_id}',   array('as' => 'rpc.menu.loadNode', 'uses' => 'Rpc\RpcMenuController@loadNode'));
    Route::post('menu/saveNode',   array('as' => 'rpc.menu.saveNode', 'uses' => 'Rpc\RpcMenuController@saveNode'));
    Route::get('menu/deleteNode/{node_id}',   array('as' => 'rpc.menu.deleteNode', 'uses' => 'Rpc\RpcMenuController@deleteNode'));
    Route::post('menu/saveTaxonomy',   array('as' => 'rpc.menu.saveTaxonomy', 'uses' => 'Rpc\RpcMenuController@saveTaxonomy'));
    Route::get('menu/loadMenu/{menu_id}/{language_id}',   array('as' => 'rpc.menu.loadMenu', 'uses' => 'Rpc\RpcMenuController@loadMenu'));
    Route::get('menu/duplicateMenu/{menu_id}/{source_language_id}/{destination_language_id}',   array('as' => 'rpc.menu.duplicateMenu', 'uses' => 'Rpc\RpcMenuController@duplicateMenu'));
});

app/Models/Article.php
<?php namespace App\Models;

use Config;
 
class Article extends Translatable {
        
    protected $table = 'blm_article';
    protected $translatable_fields = Array('name', 'summary','description');
    protected $searchable_fields = Array('name', 'summary', 'description');
    
    protected $validation_rules = Array(
                                        'label' => 'required'
                                        );
   
    
    
    protected $dates = array('date');
    private static $current_language;
       
    
    // ACCESSORS & MUTATORS
 
    public function getDateAttribute($value){
        $date_formatted = implode('/',array_reverse(explode('-',$value)));
        if($date_formatted == '00/00/0000')
            $date_formatted = '';
        return $date_formatted;
    }
    
    public function setDateAttribute($value){
        $date_formatted = implode('-',array_reverse(explode('/',$value)));
         $this->attributes['date'] = $date_formatted;
    }
    
    // RELATIONS

    public function category()
    {
        return $this->belongsToMany('App\Models\ArticleCategory', 'blm_article_article_category', 'article_id', 'article_category_id');
    }
    
}

?>

app/Http/Controllers/Admin/ArticleController.php
<?php
namespace App\Http\Controllers\Admin;


use App\Http\Controllers\AdminController;

use Auth, BaseController, Form, Input, Redirect, Sentry, View, Notification, Config;

use Article;
use ArticleCategory;

use Language;
use Tag;
use Content;


class ArticleController extends AdminController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
                $rows = new Article;
                
                
                
                $rows = $rows->filter($this->search_string);
                
                
                $article_category_id = Input::get('article_category_id');
                if($article_category_id){
                   $rows = $rows->whereHas('category', function ($query) use ($article_category_id) {
                        $query->where('blm_article_category.id', '=', $article_category_id);
                    });
                }
                
                $rows = $rows->with('category')->paginate(Config::get('bloom.admin_items_per_page'));
                
		return View::make('admin.Article.list')
                        ->with('search' , $this->search_string)
                        ->with('rows' , $rows)
                        ->with('options_category' , collection_options(ArticleCategory::get(), 'label'))
                        ->with('query_string' , $this->query_string);
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
            
                        
            // uso il modulo generico, passandogli i parametri che servono per la personalizzazione
            
            $form = Array(
                'breadcrumbs' =>  Array(
                    'Dashboard' => route('admin.dashboard') ,
                    'Articoli' => route('admin.Article.index'),
                    'Modulo' => ''
                    ),
                'action' => 'admin.Article.store',
                'model_name' => 'Article'
                
            );
            
            
                        
            return View::make('admin.Article.form')
                    ->with('tags_favourites', Tag::favourites(10))  
                    ->with('form', $form)
                    ->with('categories', ArticleCategory::all());
                
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
            
 
            if (Article::validate()){
				$record = new Article;
                $record->label = Input::get('label');
                $record->name = Language::encodeTranslations(Input::get('name'));
                $record->summary = Language::encodeTranslations(Input::get('summary'));
                $record->description = Language::encodeTranslations(Input::get('description'));
                $record->date = Input::get('date');
                $record->online = Input::get('online');
              
                $record->save();
                
                $record->category()->sync(is_array(Input::get('category'))?Input::get('category'):Array());
                
                $tags_array = explode(',', Input::get('tags'));
                $tags = Tag::find_or_create($tags_array);
                $record->tag()->sync($tags);
                
                
                
            
              
                Notification::success('Record salvato correttamente.');
                return Redirect::route('admin.Article.edit', $record->id);
            }
            
            return Redirect::back()->withInput()->withErrors(Article::$errors['validation']);
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
            $record = Article::with('tag')->find($id);
            
             // uso il modulo generico, passandogli i parametri che servono per la personalizzazione
            
            $form = Array(
                'title' => $record->label,
                'breadcrumbs' =>  Array(
                    'Dashboard' => route('admin.dashboard') ,
                    'Articoli' => route('admin.Article.index'),
                    'Modulo' => ''
                    ),
                'model_name' => 'Article'
            );

            return View::make('admin.Article.form')
                        ->with('form', $form)                        
                        ->with('tags_favourites', Tag::favourites(10))                        
                        ->with('record', $record)
                        ->with('categories', ArticleCategory::all());
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
 
            if (Article::validate()){
		$record = Article::find($id);
                $record->label = Input::get('label');
                $record->name = Language::encodeTranslations(Input::get('name'));
                $record->summary = Language::encodeTranslations(Input::get('summary'));
                $record->description = Language::encodeTranslations(Input::get('description'));
                $record->date = Input::get('date');
                $record->online = Input::get('online');
                
                $record->save();
                
                $record->category()->sync(is_array(Input::get('category'))?Input::get('category'):Array());
                
                $tags_array = explode(',', Input::get('tags'));
                $tags = Tag::find_or_create($tags_array);
                $record->tag()->sync($tags);
                                
             
                Notification::success('Record salvato correttamente.');
                return Redirect::route('admin.Article.edit', $record->id);
            }
            
            return Redirect::back()->withInput()->withErrors(Article::$errors['validation']);
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$record = Article::find($id);
                $record->delete();
                Notification::success('Record cancellato correttamente.');
                return Redirect::route('admin.Article.index');
                
	}

}

app/Http/Controllers/Www/ArticleController.php
<?php 
namespace App\Http\Controllers\Www;

use App\Http\Controllers\PublicController;

use Auth, Form, Input, Redirect, Sentry, View, Notification, Config;

use Meta;
use Article;
use ArticleCategory;

class ArticleController extends PublicController {
    
    function show($article_id, $description = null){
        
        $article = Article::enableTranslation()->with('picture', 'attachment')->find($article_id);
        
        Meta::set('title', $article->name);
        Meta::set('description', $article->description);
        if(@$article->picture->first())
            Meta::set('image', asset(@$article->picture->first()->filename));
        
        return View::make('www.Article.show')
                ->with('article', $article);
         
    }
    
    function category($category_id, $description = null){
        
        Article::enableTranslation();
        $category = ArticleCategory::enableTranslation()->with('article', 'picture', 'attachment')->find($category_id);
        
        Meta::set('title', $category->name);
        Meta::set('description', $category->description);
        if($category->picture->first())
            Meta::set('image', asset($category->picture->first()->filename));
        
        return View::make('www.ArticleCategory.show')
                ->with('category', $category);
    }
    
    
    
}

resources/views/admin/Article/form.blade.php
@extends('admin._layouts.content_form')
 
@section('form_content')
 



@if (isset($record))
    {!! Form::model($record, array('route' => Array('admin.Article.update', $record->id), 'role' => 'form', 'method' => 'PUT')) !!}
@else
    {!! Form::open(array('role' => 'form', 'route' => 'admin.Article.store', 'method' => 'POST')) !!}
@endif
          
 
            <div class="form-group">
                {!! Form::label('label', 'Etichetta') !!}
                {!! Form::text('label', null, Array('class'=> 'form-control' ,'placeholder' => 'label')) !!}
            </div>
            
            <div class="form-group">
            {!! Form::label('name', 'Nome') !!}
            {!! Language::multilanguageWidget('name',  Language::decodeTranslations(@$record->name), null, false) !!}
            </div>

            <div class="form-group">
            {!! Form::label('summary', 'Sottotitolo') !!}
            {!! Language::multilanguageWidget('summary',  Language::decodeTranslations(@$record->summary), null, false) !!}
            </div>
            
            <div class="form-group">
            {!! Form::label('name', 'Descrizione') !!}
            {!! Language::multilanguageWidget('description',  Language::decodeTranslations(@$record->description)) !!}
            </div>
            
            <div class="row">
                <div class="col-sm-6">
                    {!! Form::label('date', 'Date') !!}
                    {!! Form::text('date', null, Array('class'=> 'form-control datepicker' ,'placeholder' => 'label')) !!}      
                </div>
                <div class="col-sm-3">
                    <div class="checkbox">
                        <br/>
                        <label for="online">{!! Form::checkbox('online', 1) !!} Online</label>
                    </div>
                </div>
            </div>
            

            <div class="panel panel-default panel-form">
                <div class="panel-body">
                    <label>Categorie</label>
                    <div class="row">

                    <?php
                    $category_checked = Array();
                    if(null !== (@$record->category)){
                        foreach(@$record->category as $item){
                            $category_checked[] = $item->id;    
                        }
                    }

                    ?>
                    @if(count($categories)> 0)

                        <?php $i = 0 ?>
                        @foreach($categories as $row)
                            <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
                                <div class="checkbox">
                                    <label >
                                        {!! Form::checkbox('category['.$row->id.']', $row->id, in_array($row->id,$category_checked)) !!}
                                        <span>{!! $row->label !!}</span>
                                    </label>
                                </div>
                            </div>
                            <?php $i++; ?>
                        @endforeach
                        
                    @endif
                
                    </div>
                </div>
            </div>

            @include('admin._partials.tags_manager')
            
            <div class="form-actions">
                {!! Form::submit('Salva', array('class' => 'btn btn-block btn-primary')) !!}
            </div>
 
        {!! Form::close() !!}
@stop

resources/views/admin/Article/list.blade.php
@extends('admin._layouts.default')
 
@section('main')

<ol class="breadcrumb">
    <li><a href="{!! route('admin.dashboard') !!}">Dashboard</a></li>
    
    <li class="active">Articoli</li>
</ol>


 
<h1>Articoli - Elenco</h1>

<div class="well">
    
    <div class="row">
        <div class="col-sm-4">
            Record trovati: <strong>{!! $rows->total() !!}</strong> - <a href="{!!URL::route('admin.Article.create')!!}" class="btn btn-primary btn-sm">Nuovo Record</a>
        </div>
        <div class="col-sm-8">
            <div class="pull-right">
                {!! Form::open(array('role' => 'form', 'route' => 'admin.Article.index', 'method' => 'GET', 'class' => 'form-inline'))!!}
                <div class="form-group">
                    {!! Form::select('article_category_id', $options_category, Input::get('article_category_id'), Array('class' => 'form-control input-sm')) !!}
                </div>
                <div class="form-group">
                    <div class="input-group">
                    <input type="text" name="search" class="form-control input-sm" value="{!! $search !!}">
                        <span class="input-group-btn">
                            <button class="btn btn-default btn-sm" type="submit">Cerca</button>
                        </span>
                    </div>
                </div>
                {!! Form::close() !!}
           </div>
        </div>
    </div>

</div>

{!! Notification::showAll() !!}

@if (count($rows) > 0)
    <table class="table table-hover ">
        <thead>
            <tr>
                <th>ID</th>
                <th>Online</th>
                <th>Etichetta</th>
                <th>Categorie</th>
                
                
                <th>&nbsp;</th>
            </tr>
        </thead>
        
    @foreach ($rows as $row)
        <tr>
            <td><span class="badge">{!! $row->id !!}</span></td>
            <td>{!! $row->online?'<span class="label label-icon label-success"><span class=" glyphicon glyphicon-ok-circle"></span></span>':'<span class="label label-danger label-icon"><span class="glyphicon glyphicon-remove-circle"></span></span>'!!}</td>
            <td><strong>{!! $row->label !!}</strong></td>
            <td>
                @foreach($row->category as $item)
                    <a href="{!! route('admin.Article.index') !!}?article_category_id={!! $item->id !!}"><span class="label label-primary">{!! $item->label !!}</span></a>
                @endforeach
                
            </td>
            <td class="text-right">
                <a href="{!!URL::route('admin.Article.edit', $row->id)!!}" class="btn btn-primary">Modifica</a>
                {!! Form::open(array('route' => array('admin.Article.destroy', $row->id), 'method' => 'delete', 'class' => 'form-delete')) !!}
                        <button type="submit" href="{!! URL::route('admin.Article.destroy', $row->id) !!}" class="btn btn-danger btn-mini">Cancella</button>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </table>
    {!! $rows->appends($query_string)->render() !!}
@else
    <div class="alert alert-default">Nessun record trovato</div>
@endif


@stop