app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

// PUBLIC
Route::get('/', array('as' => 'public.homepage',       'uses' => 'Www\MainController@homepage'));
Route::get('/article/{article_id}/{article_slug?}', array('as' => 'public.article.show',       'uses' => 'Www\ArticleController@show'));
Route::get('/category/{category_id}/{category_slug?}', array('as' => 'public.category.show',       'uses' => 'Www\ArticleController@category'));



// ADMINISTRATION
Route::get('admin/login',   array('as' => 'admin.login',       'uses' => 'Admin\DashboardController@login'));


Route::get('facebook/login',   array('as' => 'facebook.login',       'uses' => 'Auth\SocialiteController@redirectToProvider'));
Route::get('facebook/check',   array('as' => 'facebook.check',       'uses' => 'Auth\SocialiteController@handleProviderCallback'));

Route::group(array('prefix' => 'admin', 'middleware' => 'bloom.auth'), function(){
    
    //Route::get('dashboard',   array('as' => 'admin.dashboard',       'uses' => 'Admin\DashboardController@index'));
    Route::get('dashboard',   array('as' => 'admin.dashboard',       'uses' => 'Admin\DashboardController@index'));
    Route::resource('Article', 'Admin\ArticleController');
    
    Route::resource('User', 'Admin\UserController');
    Route::resource('Group', 'Admin\GroupController');
    Route::resource('Language', 'Admin\LanguageController');
    Route::resource('ArticleCategory', 'Admin\ArticleCategoryController');
   
    Route::resource('Carousel', 'Admin\CarouselController');
    Route::resource('Menu', 'Admin\MenuController');
    
    Route::get('settings',   array('as' => 'admin.settings',       'uses' => 'Admin\SettingsController@index')); 
    Route::post('settings/save',   array('as' => 'admin.settings.save',       'uses' => 'Admin\SettingsController@save')); 
    Route::get('settings/delete/{group}/{key}',   array('as' => 'admin.settings.delete',       'uses' => 'Admin\SettingsController@delete')); 
});


// RPC
Route::group(array('prefix' => 'rpc'), function(){
    
    // Autenticazione
    Route::post('login',   array('as' => 'rpc.login', 'uses' => 'Rpc\RpcAuthController@postLogin'));
    Route::get('logout',   array('as' => 'rpc.logout', 'uses' => 'Rpc\RpcAuthController@getLogout'));
    
    // Form - immagini
    Route::post('form/upload/picture',   array('as' => 'rpc.form.upload.picture', 'uses' => 'Rpc\RpcFormController@uploadPicture'));
    Route::get('form/delete/picture',   array('as' => 'rpc.form.delete.picture', 'uses' => 'Rpc\RpcFormController@deletePicture'));
    Route::get('form/load/pictures',   array('as' => 'rpc.form.load.pictures', 'uses' => 'Rpc\RpcFormController@loadPictures'));
    Route::get('form/setMain/picture',   array('as' => 'rpc.form.setmain.picture', 'uses' => 'Rpc\RpcFormController@setMainPicture'));
    Route::post('form/rename/picture',   array('as' => 'rpc.form.rename.picture', 'uses' => 'Rpc\RpcFormController@renamePicture'));
    Route::get('form/setOrder/picture',   array('as' => 'rpc.form.setorder.picture', 'uses' => 'Rpc\RpcFormController@setOrderPicture'));
    
    
    // Form - allegati
    Route::post('form/upload/attachment',   array('as' => 'rpc.form.upload.attachment', 'uses' => 'Rpc\RpcFormController@uploadAttachment'));
    Route::get('form/delete/attachment',   array('as' => 'rpc.form.delete.attachment', 'uses' => 'Rpc\RpcFormController@deleteAttachment'));
    Route::get('form/load/attachments',   array('as' => 'rpc.form.load.attachments', 'uses' => 'Rpc\RpcFormController@loadAttachments'));
    Route::post('form/rename/attachment',   array('as' => 'rpc.form.rename.attachment', 'uses' => 'Rpc\RpcFormController@renameAttachment'));
    Route::get('form/setOrder/attachment',   array('as' => 'rpc.form.setorder.attachment', 'uses' => 'Rpc\RpcFormController@setOrderAttachment'));
    
    // Menu
    Route::get('menu/loadNode/{node_id}',   array('as' => 'rpc.menu.loadNode', 'uses' => 'Rpc\RpcMenuController@loadNode'));
    Route::post('menu/saveNode',   array('as' => 'rpc.menu.saveNode', 'uses' => 'Rpc\RpcMenuController@saveNode'));
    Route::get('menu/deleteNode/{node_id}',   array('as' => 'rpc.menu.deleteNode', 'uses' => 'Rpc\RpcMenuController@deleteNode'));
    Route::post('menu/saveTaxonomy',   array('as' => 'rpc.menu.saveTaxonomy', 'uses' => 'Rpc\RpcMenuController@saveTaxonomy'));
    Route::get('menu/loadMenu/{menu_id}/{language_id}',   array('as' => 'rpc.menu.loadMenu', 'uses' => 'Rpc\RpcMenuController@loadMenu'));
    Route::get('menu/duplicateMenu/{menu_id}/{source_language_id}/{destination_language_id}',   array('as' => 'rpc.menu.duplicateMenu', 'uses' => 'Rpc\RpcMenuController@duplicateMenu'));
});

app/Models/Carousel.php
<?php namespace App\Models;

use Config;

 
class Carousel extends Translatable {
 
    protected $table = 'blm_carousel';
    protected $translatable_fields = Array('name','summary');
    protected $searchable_fields = Array('name','summary');
    
    protected $validation_rules = Array(
                                     'label' => 'required'
                                     );
  
}

?>

app/Http/Controllers/Admin/CarouselController.php
<?php 

namespace App\Http\Controllers\Admin;


use App\Http\Controllers\AdminController;

use Auth, BaseController, Form, Input, Redirect, Sentry, View, Notification, Config;


use Carousel;

use Language;
use Tag;
use Content;




class CarouselController extends AdminController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
                $rows = new Carousel;
                
                if($this->search_string){
                    $rows = $rows->filter(Array('search' => $this->search_string));
                }
                
                $rows = $rows->paginate(Config::get('bloom.admin_items_per_page'));
                
		return View::make('admin.Carousel.list')
                        ->with('search' , $this->search_string)
                        ->with('rows' , $rows)
                        ->with('query_string' , $this->query_string);
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
                        
            // uso il modulo generico, passandogli i parametri che servono per la personalizzazione
            
            $form = Array(
                'breadcrumbs' =>  Array(
                    'Dashboard' => route('admin.dashboard') ,
                    'Carousel' => route('admin.Carousel.index'),
                    'Modulo' => ''
                    ),
                'action' => 'admin.Carousel.store',
                'model_name' => 'Carousel',
                'hide_pictures' => true,
                'hide_attachments' => true,
                
            );
            
            return View::make('admin.Carousel.form')
                    ->with('tags_favourites', Tag::favourites(10))  
                    ->with('form', $form);
                
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
 
            if (Carousel::validate()){
		$record = new Carousel;
                $record->label = Input::get('label');
                $record->name = Language::encodeTranslations(Input::get('name'));
                $record->summary = Language::encodeTranslations(Input::get('summary'));
                $record->online = Input::get('online');
                $record->image = $record->handleUpload('image', Config::get('bloom.public_images_upload_folder'));
                $record->save();
                
                $tags_array = explode(',', Input::get('tags'));
                $tags = Tag::find_or_create($tags_array);
                $record->tag()->sync($tags);
            
              
                Notification::success('Record salvato correttamente.');
                return Redirect::route('admin.Carousel.edit', $record->id);
            }
            
            return Redirect::back()->withInput()->withErrors(Carousel::$errors['validation']);
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
            $record = Carousel::with('tag')->find($id);
            
             // uso il modulo generico, passandogli i parametri che servono per la personalizzazione
            
            $form = Array(
                'title' => $record->label,
                'breadcrumbs' =>  Array(
                    'Dashboard' => route('admin.dashboard') ,
                    'Carousel' => route('admin.Carousel.index'),
                    'Modulo' => ''
                    ),
                'model_name' => 'Carousel',
                'hide_pictures' => true,
                'hide_attachments' => true,
                
            );

            return View::make('admin.Carousel.form')
                        ->with('form', $form)                        
                        ->with('tags_favourites', Tag::favourites(10))                        
                        ->with('record', $record);
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
 
            if (Carousel::validate()){
		$record = Carousel::find($id);
                $record->label = Input::get('label');
                $record->name = Language::encodeTranslations(Input::get('name'));
                $record->summary = Language::encodeTranslations(Input::get('summary'));
                $record->online = Input::get('online');
                $record->image = $record->handleUpload('image', Config::get('bloom.public_images_upload_folder'));
                
                $record->save();
                
                $tags_array = explode(',', Input::get('tags'));
                $tags = Tag::find_or_create($tags_array);
                $record->tag()->sync($tags);
                                
             
                Notification::success('Record salvato correttamente.');
                return Redirect::route('admin.Carousel.edit', $record->id);
            }
            
            return Redirect::back()->withInput()->withErrors(Carousel::$errors['validation']);
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$record = Carousel::find($id);
                $record->delete();
                
                // TODO: cancellare l'immagine
                
                Notification::success('Record cancellato correttamente.');
                return Redirect::route('admin.Carousel.index');
	}

}

resources/views/admin/Carousel/form.blade.php
@extends('admin._layouts.content_form')
 
@section('form_content')
 



@if (isset($record))
    {!! Form::model($record, array('route' => Array('admin.Carousel.update', $record->id), 'role' => 'form', 'method' => 'PUT', 'files' => true)) !!}
@else
    {!! Form::open(array('role' => 'form', 'route' => 'admin.Carousel.store', 'method' => 'POST', 'files' => true)) !!}
@endif
            @if ($errors->has('login'))
                <div class="alert alert-error">{!! $errors->first('login', ':message') !!}</div>
            @endif
            
            <div class="row">
                <div class="col-sm-8">
                    <div class="form-group">
                        {!! Form::label('label', 'Etichetta') !!}
                        {!! Form::text('label', null, Array('class'=> 'form-control' ,'placeholder' => 'label')) !!}
                    </div>
                </div>
                <div class="col-sm-4">
                     <div class="checkbox">
                         <br/>
                        <label for="online">{!! Form::checkbox('online', 1) !!} Online</label>
                    </div>
                </div>
            </div>
            
            
            <div class="form-group">
            {!! Form::label('name', 'Nome') !!}
            {!! Language::multilanguageWidget('name',  Language::decodeTranslations(@$record->name), null, false) !!}
            </div>
            
            <div class="form-group">
            {!! Form::label('summary', 'Sommario') !!}
            {!! Language::multilanguageWidget('summary',  Language::decodeTranslations(@$record->summary), null, false) !!}
            </div>
            
            @include('admin._partials.picture_form', Array('input_name' => 'image', 'label' => 'Immagine', 'filename' => @$record->image))
            
            <div class="form-actions">
                {!! Form::submit('Salva', array('class' => 'btn btn-block btn-primary')) !!}
            </div>
 
        {!! Form::close() !!}
@stop

resources/views/admin/Carousel/list.blade.php
@extends('admin._layouts.default')
 
@section('main')

<ol class="breadcrumb">
    <li><a href="{!! route('admin.dashboard') !!}">Dashboard</a></li>
    
    <li class="active">Carousel</li>
</ol>


 
<h1>Carousel - Elenco</h1>

<div class="well">
    
    <div class="row">
        <div class="col-sm-9">
            Record trovati: <strong>{!! $rows->total() !!}</strong> - <a href="{!!URL::route('admin.Carousel.create')!!}" class="btn btn-primary btn-sm">Nuovo Record</a>
        </div>
        <div class="col-sm-3">
            <div class="pull-right">
                {!! Form::open(array('role' => 'form', 'route' => 'admin.Carousel.index', 'method' => 'GET', 'class' => 'form-inline')) !!}
                <div class="form-group">
                    <div class="input-group">
                    <input type="text" name="search" class="form-control input-sm" value="{!! $search !!}">
                        <span class="input-group-btn">
                            <button class="btn btn-default btn-sm" type="submit">Cerca</button>
                        </span>
                    </div>
                </div>
                {!! Form::close() !!}
           </div>
        </div>
    </div>

</div>

{!! Notification::showAll() !!}

@if (count($rows) > 0)
    <table class="table table-hover ">
        <thead>
            <tr>
                <th>&nbsp;</th>
                <th>ID</th>
                <th>Online</th>
                <th>Etichetta</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        
    @foreach ($rows as $row)
        <tr>
            
            <td>
                @if(!empty($row->image))
                    <img src="{!! Image::resize($row->image, Config::get('bloom.admin_thumbnail_width'), Config::get('bloom.admin_thumbnail_height'), true) !!}" class="img-thumbnail"></td>
                @endif
            <td><span class="badge">{!! $row->id !!}</span></td>
            <td>{!! $row->online?'<span class="label label-icon label-success"><span class=" glyphicon glyphicon-ok-circle"></span></span>':'<span class="label label-danger label-icon"><span class="glyphicon glyphicon-remove-circle"></span></span>'!!}</td>
            <td><strong>{!! $row->label !!}</strong></td>
            <td class="text-right">
                <a href="{!!URL::route('admin.Carousel.edit', $row->id)!!}" class="btn btn-primary">Modifica</a>
                {!! Form::open(array('route' => array('admin.Carousel.destroy', $row->id), 'method' => 'delete', 'class' => 'form-delete')) !!}
                        <button type="submit" href="{!! URL::route('admin.Carousel.destroy', $row->id) !!}" class="btn btn-danger btn-mini">Cancella</button>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </table>
    {!! $rows->appends($query_string)->render() !!}
@else
    <div class="alert alert-default">Nessun record trovato</div>
@endif


@stop