app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

// PUBLIC
Route::get('/', array('as' => 'public.homepage',       'uses' => 'Www\MainController@homepage'));
Route::get('/article/{article_id}/{article_slug?}', array('as' => 'public.article.show',       'uses' => 'Www\ArticleController@show'));
Route::get('/category/{category_id}/{category_slug?}', array('as' => 'public.category.show',       'uses' => 'Www\ArticleController@category'));



// ADMINISTRATION
Route::get('admin/login',   array('as' => 'admin.login',       'uses' => 'Admin\DashboardController@login'));


Route::get('facebook/login',   array('as' => 'facebook.login',       'uses' => 'Auth\SocialiteController@redirectToProvider'));
Route::get('facebook/check',   array('as' => 'facebook.check',       'uses' => 'Auth\SocialiteController@handleProviderCallback'));

Route::group(array('prefix' => 'admin', 'middleware' => 'bloom.auth'), function(){
    
    //Route::get('dashboard',   array('as' => 'admin.dashboard',       'uses' => 'Admin\DashboardController@index'));
    Route::get('dashboard',   array('as' => 'admin.dashboard',       'uses' => 'Admin\DashboardController@index'));
    Route::resource('Article', 'Admin\ArticleController');
    
    Route::resource('User', 'Admin\UserController');
    Route::resource('Group', 'Admin\GroupController');
    Route::resource('Language', 'Admin\LanguageController');
    Route::resource('ArticleCategory', 'Admin\ArticleCategoryController');
   
    Route::resource('Carousel', 'Admin\CarouselController');
    Route::resource('Menu', 'Admin\MenuController');
    
    Route::get('settings',   array('as' => 'admin.settings',       'uses' => 'Admin\SettingsController@index')); 
    Route::post('settings/save',   array('as' => 'admin.settings.save',       'uses' => 'Admin\SettingsController@save')); 
    Route::get('settings/delete/{group}/{key}',   array('as' => 'admin.settings.delete',       'uses' => 'Admin\SettingsController@delete')); 
});


// RPC
Route::group(array('prefix' => 'rpc'), function(){
    
    // Autenticazione
    Route::post('login',   array('as' => 'rpc.login', 'uses' => 'Rpc\RpcAuthController@postLogin'));
    Route::get('logout',   array('as' => 'rpc.logout', 'uses' => 'Rpc\RpcAuthController@getLogout'));
    
    // Form - immagini
    Route::post('form/upload/picture',   array('as' => 'rpc.form.upload.picture', 'uses' => 'Rpc\RpcFormController@uploadPicture'));
    Route::get('form/delete/picture',   array('as' => 'rpc.form.delete.picture', 'uses' => 'Rpc\RpcFormController@deletePicture'));
    Route::get('form/load/pictures',   array('as' => 'rpc.form.load.pictures', 'uses' => 'Rpc\RpcFormController@loadPictures'));
    Route::get('form/setMain/picture',   array('as' => 'rpc.form.setmain.picture', 'uses' => 'Rpc\RpcFormController@setMainPicture'));
    Route::post('form/rename/picture',   array('as' => 'rpc.form.rename.picture', 'uses' => 'Rpc\RpcFormController@renamePicture'));
    Route::get('form/setOrder/picture',   array('as' => 'rpc.form.setorder.picture', 'uses' => 'Rpc\RpcFormController@setOrderPicture'));
    
    
    // Form - allegati
    Route::post('form/upload/attachment',   array('as' => 'rpc.form.upload.attachment', 'uses' => 'Rpc\RpcFormController@uploadAttachment'));
    Route::get('form/delete/attachment',   array('as' => 'rpc.form.delete.attachment', 'uses' => 'Rpc\RpcFormController@deleteAttachment'));
    Route::get('form/load/attachments',   array('as' => 'rpc.form.load.attachments', 'uses' => 'Rpc\RpcFormController@loadAttachments'));
    Route::post('form/rename/attachment',   array('as' => 'rpc.form.rename.attachment', 'uses' => 'Rpc\RpcFormController@renameAttachment'));
    Route::get('form/setOrder/attachment',   array('as' => 'rpc.form.setorder.attachment', 'uses' => 'Rpc\RpcFormController@setOrderAttachment'));
    
    // Menu
    Route::get('menu/loadNode/{node_id}',   array('as' => 'rpc.menu.loadNode', 'uses' => 'Rpc\RpcMenuController@loadNode'));
    Route::post('menu/saveNode',   array('as' => 'rpc.menu.saveNode', 'uses' => 'Rpc\RpcMenuController@saveNode'));
    Route::get('menu/deleteNode/{node_id}',   array('as' => 'rpc.menu.deleteNode', 'uses' => 'Rpc\RpcMenuController@deleteNode'));
    Route::post('menu/saveTaxonomy',   array('as' => 'rpc.menu.saveTaxonomy', 'uses' => 'Rpc\RpcMenuController@saveTaxonomy'));
    Route::get('menu/loadMenu/{menu_id}/{language_id}',   array('as' => 'rpc.menu.loadMenu', 'uses' => 'Rpc\RpcMenuController@loadMenu'));
    Route::get('menu/duplicateMenu/{menu_id}/{source_language_id}/{destination_language_id}',   array('as' => 'rpc.menu.duplicateMenu', 'uses' => 'Rpc\RpcMenuController@duplicateMenu'));
});

app/Models/Group.php
<?php namespace App\Models;

//use User;

class Group extends \Eloquent {

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
    
    protected $table = 'groups';
        
    public function user(){
        return $this->belongsToMany('App\User', 'users_groups', 'group_id', 'user_id');
    }
  
}

app/Http/Controllers/Admin/GroupController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\AdminController;
use BaseController, Form, Input, Redirect, Sentry, View, Notification, Config;
use App\Models\Group;


use App\Services\Validators\GroupValidator;

class GroupController extends AdminController{
        
        var $admin_group_id = null;
    
        public function __construct(){
            parent::__construct();
            
            
        }

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
                $rows = Group::with('user');
                
                $rows = $rows->paginate(Config::get('bloom.admin_items_per_page'));
                
                $query_string = array_except(Input::all(), array('page'));
                
		return View::make('admin.Group.list')
                        ->with('rows' , $rows)
                        ->with('admin_group_id' , $this->admin_group_id)
                        ->with('query_string' , $query_string);
                
                
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
            
            $record = new Group;
            
          
              
            return View::make('admin.Group.form')
                        ->with('record' , $record);
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
            $validation = new GroupValidator;
 
            if ($validation->passes()){
		$record = new Group;
                $record->name = Input::get('name');
                $record->description = Input::get('description');
                $record->save();
                
                                
                Notification::success('Record salvato correttamente.');
                return Redirect::route('admin.Group.edit', $record->id);
            }
            
            return Redirect::back()->withInput()->withErrors($validation->errors);
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
            
            
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
            $record = Group::find($id);
            
            return View::make('admin.Group.form')
            
                        ->with('record' , $record);
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
            $validation = new GroupValidator;
 
            if ($validation->passes()){
		$record = Group::find($id);
                $record->name = Input::get('name');
                $record->description = Input::get('description');
                $record->save();
                
                              
                Notification::success('Record salvato correttamente.');
                return Redirect::route('admin.Group.edit', $record->id);
            }
            
            return Redirect::back()->withInput()->withErrors($validation->errors);
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
                if($id != $this->admin_group_id){
                    $record = Group::find($id);
                
                    $record->delete();
                
                    Notification::success('Record cancellato correttamente.');
                    return Redirect::route('admin.Group.index');
                }
                else{
                    Notification::success('Impossibile cancellare il gruppo degli amministratori');
                    return Redirect::route('admin.Group.index');
                    
                }
	}

}

resources/views/admin/Group/form.blade.php
@extends('admin._layouts.default')
 
@section('main')
 
<ol class="breadcrumb">
    <li><a href="{!! route('admin.dashboard') !!}">Dashboard</a></li>
    <li><a href="{!! route('admin.Group.index') !!}">Gruppi</a></li>
    <li class="active">Modulo</li>
</ol>



@include('admin._partials.form_header', ['title' => $record->name])



{!! Notification::showAll() !!}
 
@if ($errors->any())
        <div class="alert alert-danger">
                {!! implode('<br>', $errors->all()) !!}
        </div>
@endif



{{-- INIZIO SEZIONE MAIN --}}
@if (isset($record->id))
    {!! Form::model($record, array('route' => Array('admin.Group.update', $record->id), 'role' => 'form', 'method' => 'PUT')) !!}
@else
    {!! Form::open(array('role' => 'form', 'route' => 'admin.Group.store', 'method' => 'POST')) !!}
@endif
            @if ($errors->has('login'))
                <div class="alert alert-error">{!! $errors->first('login', ':message') !!}</div>
            @endif
 
            <div class="form-group">
                {!! Form::label('name', 'Nome') !!}
                {!! Form::text('name', null, Array('class'=> 'form-control' ,'placeholder' => 'name')) !!}
            </div>
            
            <div class="form-group">
                {!! Form::label('description', 'Descrizione') !!}
                {!! Form::textarea('description', null, Array('class'=> 'form-control' ,'placeholder' => 'name')) !!}
            </div>
             
            
            <div class="form-actions">
                {!! Form::submit('Salva', array('class' => 'btn btn-block btn-primary')) !!}
            </div>
 
        {!! Form::close() !!}
{{-- FINE SEZIONE GENERALE --}}


@stop

resources/views/admin/Group/list.blade.php
@extends('admin._layouts.default')
 
@section('main')
 
<ol class="breadcrumb">
    <li><a href="{!! route('admin.dashboard') !!}">Dashboard</a></li>
    <li class="active">Gruppi</li>
</ol>
 

<h1>Gruppi di Account - Elenco</h1>
<p><strong>Attenzione</strong>: Il gruppo degli amministratori non pu&ograve; essere modificato o cancellato.</p>

<div class="well well-sm">
    <div class="row">
        <div class="col-sm-12">
            Record trovati: <strong>{!! $rows->total() !!}</strong> - <a href="{!!URL::route('admin.Group.create')!!}" class="btn btn-primary btn-sm">Nuovo Record</a>
        </div>
        
    </div>
</div>

{!! Notification::showAll() !!}

@if (count($rows) > 0)
    <table class="table  table-hover">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nome</th>
                <th>Account</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
    @foreach ($rows as $row)
        <tr>
            <td><span class="badge">{!! $row->id !!}</span></td>
            
            <td><strong>{!! $row->name !!}</strong></td>
            <td><span class="badge">{!! count($row->user) !!}</span></td>
            
            
            <td class="text-right">
                @if($row->id != $admin_group_id)
                <a href="{!!URL::route('admin.Group.edit', $row->id)!!}" class="btn btn-primary">Modifica</a>
                {!! Form::open(array('route' => array('admin.Group.destroy', $row->id), 'method' => 'delete', 'class' => "form-delete")) !!}
                        <button type="submit" href="{!! URL::route('admin.Group.destroy', $row->id) !!}" class="btn btn-danger btn-mini">Cancella</button>
                {!! Form::close() !!}
                @else
                    <input type="button" disabled class="btn btn-danger btn-mini" value="Modifica">
                    <input type="button" disabled class="btn btn-danger btn-mini" value="Cancella">
                @endif
            </td>
                
        </tr>
    @endforeach
    </table>
    {!! $rows->appends($query_string)->render() !!}
@else
    <div class="alert alert-default">Nessun record trovato</div>
@endif


@stop