app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

// PUBLIC
Route::get('/', array('as' => 'public.homepage',       'uses' => 'Www\MainController@homepage'));
Route::get('/article/{article_id}/{article_slug?}', array('as' => 'public.article.show',       'uses' => 'Www\ArticleController@show'));
Route::get('/category/{category_id}/{category_slug?}', array('as' => 'public.category.show',       'uses' => 'Www\ArticleController@category'));



// ADMINISTRATION
Route::get('admin/login',   array('as' => 'admin.login',       'uses' => 'Admin\DashboardController@login'));


Route::get('facebook/login',   array('as' => 'facebook.login',       'uses' => 'Auth\SocialiteController@redirectToProvider'));
Route::get('facebook/check',   array('as' => 'facebook.check',       'uses' => 'Auth\SocialiteController@handleProviderCallback'));

Route::group(array('prefix' => 'admin', 'middleware' => 'bloom.auth'), function(){
    
    //Route::get('dashboard',   array('as' => 'admin.dashboard',       'uses' => 'Admin\DashboardController@index'));
    Route::get('dashboard',   array('as' => 'admin.dashboard',       'uses' => 'Admin\DashboardController@index'));
    Route::resource('Article', 'Admin\ArticleController');
    
    Route::resource('User', 'Admin\UserController');
    Route::resource('Group', 'Admin\GroupController');
    Route::resource('Language', 'Admin\LanguageController');
    Route::resource('ArticleCategory', 'Admin\ArticleCategoryController');
   
    Route::resource('Carousel', 'Admin\CarouselController');
    Route::resource('Menu', 'Admin\MenuController');
    
    Route::get('settings',   array('as' => 'admin.settings',       'uses' => 'Admin\SettingsController@index')); 
    Route::post('settings/save',   array('as' => 'admin.settings.save',       'uses' => 'Admin\SettingsController@save')); 
    Route::get('settings/delete/{group}/{key}',   array('as' => 'admin.settings.delete',       'uses' => 'Admin\SettingsController@delete')); 
});


// RPC
Route::group(array('prefix' => 'rpc'), function(){
    
    // Autenticazione
    Route::post('login',   array('as' => 'rpc.login', 'uses' => 'Rpc\RpcAuthController@postLogin'));
    Route::get('logout',   array('as' => 'rpc.logout', 'uses' => 'Rpc\RpcAuthController@getLogout'));
    
    // Form - immagini
    Route::post('form/upload/picture',   array('as' => 'rpc.form.upload.picture', 'uses' => 'Rpc\RpcFormController@uploadPicture'));
    Route::get('form/delete/picture',   array('as' => 'rpc.form.delete.picture', 'uses' => 'Rpc\RpcFormController@deletePicture'));
    Route::get('form/load/pictures',   array('as' => 'rpc.form.load.pictures', 'uses' => 'Rpc\RpcFormController@loadPictures'));
    Route::get('form/setMain/picture',   array('as' => 'rpc.form.setmain.picture', 'uses' => 'Rpc\RpcFormController@setMainPicture'));
    Route::post('form/rename/picture',   array('as' => 'rpc.form.rename.picture', 'uses' => 'Rpc\RpcFormController@renamePicture'));
    Route::get('form/setOrder/picture',   array('as' => 'rpc.form.setorder.picture', 'uses' => 'Rpc\RpcFormController@setOrderPicture'));
    
    
    // Form - allegati
    Route::post('form/upload/attachment',   array('as' => 'rpc.form.upload.attachment', 'uses' => 'Rpc\RpcFormController@uploadAttachment'));
    Route::get('form/delete/attachment',   array('as' => 'rpc.form.delete.attachment', 'uses' => 'Rpc\RpcFormController@deleteAttachment'));
    Route::get('form/load/attachments',   array('as' => 'rpc.form.load.attachments', 'uses' => 'Rpc\RpcFormController@loadAttachments'));
    Route::post('form/rename/attachment',   array('as' => 'rpc.form.rename.attachment', 'uses' => 'Rpc\RpcFormController@renameAttachment'));
    Route::get('form/setOrder/attachment',   array('as' => 'rpc.form.setorder.attachment', 'uses' => 'Rpc\RpcFormController@setOrderAttachment'));
    
    // Menu
    Route::get('menu/loadNode/{node_id}',   array('as' => 'rpc.menu.loadNode', 'uses' => 'Rpc\RpcMenuController@loadNode'));
    Route::post('menu/saveNode',   array('as' => 'rpc.menu.saveNode', 'uses' => 'Rpc\RpcMenuController@saveNode'));
    Route::get('menu/deleteNode/{node_id}',   array('as' => 'rpc.menu.deleteNode', 'uses' => 'Rpc\RpcMenuController@deleteNode'));
    Route::post('menu/saveTaxonomy',   array('as' => 'rpc.menu.saveTaxonomy', 'uses' => 'Rpc\RpcMenuController@saveTaxonomy'));
    Route::get('menu/loadMenu/{menu_id}/{language_id}',   array('as' => 'rpc.menu.loadMenu', 'uses' => 'Rpc\RpcMenuController@loadMenu'));
    Route::get('menu/duplicateMenu/{menu_id}/{source_language_id}/{destination_language_id}',   array('as' => 'rpc.menu.duplicateMenu', 'uses' => 'Rpc\RpcMenuController@duplicateMenu'));
});

resources/views/admin/_partials/footer.blade.php
<div class="container text-center">
    
    @if($current_user)
        {{ $current_user->name }} -  
    @endif
    &copy; {!! date('Y') !!} Bloom Design
    
</div>

resources/views/admin/_partials/form_header.blade.php
<div class="row form-header">
    <div class="col-sm-9">
        <h1>
            @if(@isset($title))
                {!! $title !!}
            @else
                Nuovo Record
            @endif
        </h1>

    </div> 
    <div class="col-sm-3 text-right">
        @if(isset($record->id))
        <div class="record-info">
            Creazione: <strong>{!! $record->created_at !!}</strong><br/>
            Ultima modifica: <strong>{!! $record->updated_at !!}</strong>
        </div>
        @endif
    </div>    
</div>

resources/views/admin/_partials/navbar-side.blade.php
      <ul class="nav nav-sidebar">
        
          
        <li class="dropdown">
          <a href="#"  role="button" aria-expanded="false">Contenuti</span></a>
          <ul role="menu">
            <li><a href="{!! URL::route('admin.Article.index') !!}">Articoli</a></li>
            <li><a href="{!! URL::route('admin.ArticleCategory.index') !!}">Categorie di articoli</a></li>
            <li><a href="{!! URL::route('admin.Carousel.index') !!}">Carousel</a></li>
            <li class="divider"></li>
            
            <li><a href="{!! URL::route('admin.Menu.index') !!}">Menu</a></li>
          </ul>
        </li>
          
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Autenticazione <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="{!! URL::route('admin.User.index') !!}">Utenti</a></li>
            <li><a href="{!! URL::route('admin.Group.index') !!}">Gruppi</a></li>
          </ul>
        </li>
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Configurazione <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="{!! URL::route('admin.Language.index') !!}">Lingue</a></li>
            <li><a href="{!! URL::route('admin.settings') !!}">Parametri</a></li>
            
          </ul>
        </li>
        
        
        <li><a href="{!! route('rpc.logout') !!}">Disconnessione</a></li>
      </ul>
     

resources/views/admin/_partials/navbar.blade.php
<nav class="navbar  navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bloom-navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">{!! Config::get('bloom.site_name') !!}</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bloom-navbar">
      <ul class="nav navbar-nav">
        
          
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Contenuti <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="{!! URL::route('admin.Article.index') !!}">Articoli</a></li>
            <li><a href="{!! URL::route('admin.ArticleCategory.index') !!}">Categorie di articoli</a></li>
            <li><a href="{!! URL::route('admin.Carousel.index') !!}">Carousel</a></li>
            <li class="divider"></li>
            
            <li><a href="{!! URL::route('admin.Menu.index') !!}">Menu</a></li>
          </ul>
        </li>
          
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Autenticazione <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="{!! URL::route('admin.User.index') !!}">Utenti</a></li>
            <li><a href="{!! URL::route('admin.Group.index') !!}">Gruppi</a></li>
          </ul>
        </li>
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Configurazione <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="{!! URL::route('admin.Language.index') !!}">Lingue</a></li>
            <li><a href="{!! URL::route('admin.settings') !!}">Parametri</a></li>
            
          </ul>
        </li>
        
        
        <li><a href="{!! route('rpc.logout') !!}">Disconnessione</a></li>
      </ul>
     
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

resources/views/admin/_partials/picture_form.blade.php
<?php
if(!isset($input_name) || $input_name == "")
    $input_name = 'file';
if(!isset($show_image) || $show_image == "")
    $show_image = false;
if(!isset($label) || $label == "")
    $label = 'Image Upload';
?>
<fieldset>
<legend>{!! $label !!}</legend>
<div class="row">

    <div class="col-sm-4 text-center ">
        
        @if(isset($filename) && $filename !='')
        <div class="well">
            <a href="{!! URL::asset($filename) !!}"><img src="{!! Image::resize($filename, 100, 100, true) !!}"  class="img-rounded red_thumb"/></a>
            <p><a target="_blank" href="{!! URL::asset($filename) !!}"><small style="word-wrap: break-word;">{!! $filename !!}</small></a></p>
        </div>
        @else
            <span class="badge">Nessun file allegato</span>
        @endif
        
    </div>
    <div class="col-sm-4">
        
        
        {!! Form::select($input_name.'_action', Array('' => 'Lascia invariato', 'add' => 'Aggiungi/sostituisci file', 'remove' => 'Rimuovi'), null, Array('rel' => $input_name, 'class' => 'form-control image-action'))!!}
        
        
        

        <div id="container_file" style="display: none;">
            <input type="file" name="{!! $input_name !!}" class="image-file" id="input_file_{!! $input_name!!}"/>
            
        </div>
        
       
    </div>
    <div class="col-sm-4">
        {!! Form::text($input_name.'_fake', null, Array('id' => $input_name.'_fake' , 'disabled' => 'disabled', 'class' => 'form-control hidden' )) !!}
        
    </div>
</div>
</fieldset>

<script>
    
$(document).ready(function(){
    if(pictureFormInitialized === undefined){
        handlePictureForm();
        var pictureFormInitialized = true;
    }
});

function handlePictureForm(){
    
    console.log('Picture form initialized');
    
    // action change 
    $('.image-action').each(function(e){
        $(this).val('');
    });
       
    // action change 
    $('.image-action').on('change', function(e){
        input_name = $(this).attr('rel');
        input_file_id = '#input_file_' + input_name;
        if($(this).val() == 'add'){
            $(input_file_id).trigger('click');
            $('#' + input_name + '_fake').removeClass('hidden');        
        }
        else{
            $('#' + input_name + '_fake').addClass('hidden');
        }
    });
    
    // filename change
    $('.image-file').on('change', function(e){
        input_name = $(this).attr('name');
        input_file_id = '#input_file_' + input_name;
        $('#' + input_name + '_fake').val( $(input_file_id).val());
    });
}    
    
  
</script>
<hr/>

resources/views/admin/_partials/tags_manager.blade.php
{{-- TAGS --}}
        <div class="panel panel-default  panel-form">
            <div class="panel-body">
                 <div class="form-group">
                     <a name="tags-container" id="tags-container"></a>
                {!! Form::label('Tags') !!}<br/>
                <input name="tags_input" id="tags_input" value="" type="text" class="input-sm tm-input tm-input-inverse form-control" style="width:150px; display: inline;" placeholder="Nuovo tag">  


                @if(isset($tags_favourites) && count($tags_favourites) > 0)
                    <p><small>

                    <strong>Preferiti</strong>&nbsp;
                     @foreach($tags_favourites as $item)
                     <a href="#tags-container" class="tags-favourite">{!! $item->name !!}</a>

                     @endforeach
                     </small></p>
                @endif
                 </div>
            </div>
        </div>
     <script>
        $(document).ready(function(){
            // TAGS
            <?php
                // Preparo la lista dei tag

                $tags_array = Array();
                if(isset($record->id)){
                    foreach($record->tag as $item){
                        $tags_array[] = $item->name;
                    }
                }
                $tags = implode(',', $tags_array);
            ?>

            $('#tags_input').tagsManager({'hiddenTagListName' : 'tags', 'prefilled' : '{!! $tags !!}'});
            $('.tags-favourite').click(function(e){
                e.preventDefault();
                $('#tags_input').tagsManager('pushTag',$(e.target).text());
            });
        });
     </script>
{{-- END TAGS --}}